version: '3.3'

volumes:
  postgres_data:
  media_value:
  static_value:

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs:/usr/share/nginx/html/api/docs
      - static_value:/var/html/api/static/
      - media_value:/var/html/media/
    depends_on:
      - web


  postgres:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    env_file:
      - ./.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 10s
      retries: 5

  web:
    image: 1kovalevskiy/foodgram_web:latest
    restart: always
    depends_on:
      - postgres
    env_file:
      - ./.env
    command: >
      sh -c "
      python manage.py collectstatic --noinput &&
      sleep 10 &&
      python manage.py migrate --noinput &&
      sleep 10 &&
      python manage.py loaddata dump.json &&
      gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - media_value:/foodgram/media/
      - static_value:/foodgram/static/
