# Generated by Django 3.2.9 on 2022-01-09 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredients',
            options={'verbose_name': 'ingredient', 'verbose_name_plural': 'ingredients'},
        ),
    ]
