# Generated by Django 3.2.9 on 2022-01-11 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20220109_1038'),
        ('ingredients', '0002_alter_ingredients_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
    ]
